### ISSUE TITLE
simDetectorAttributes.xml file points to non-existent xsi:schemaLocation

### ISSUE THREAD

**Issue by prjemian** [areaDetector/ADCore#38]
Even though a validation script exists in  ADCore / iocBoot / validateXML.sh,
this line in the file is incorrect.  XML Schema aware editors will signal this as an error.  It is useful to edit these files with schema aware editors as they flag schema-violations and offer schema-based suggestions while editing.

The problem cited is only a nuisance, does not affect operation of the HDF5 plugin.

**Comment by MarkRivers** [comment]
If the schema can be found here:
https://github.com/areaDetector/ADCore/blob/master/iocBoot/NDAttributes.xsd

what is the correct syntax to put in the simDetectorAttributes.xml file?

**Comment by prjemian** [comment]
Suggest to remove the old syntax which declared a namespace and use this one:

---: xsi:schemaLocation="http://epics.aps.anl.gov/areaDetector/attributes ../attributes.xsd"
+++: xsi:noNamespaceSchemaLocation="../../../../iocBoot/NDAttributes.xsd"

Easier still, if the XML Schema is moved into the same directory.  
Same pattern for the layout files.

see: http://www.w3.org/TR/xmlschema-1/#xsi_schemaLocation
see: http://www.w3schools.com/schema/schema_example.asp

**Comment by MarkRivers** [comment]
I changed simDetectorAttributes.xml to the following:

<?xml version="1.0" standalone="no" ?>

<Attributes
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="xsi:noNamespaceSchemaLocation="../../../../../ADCore/iocBoot/NDAttributes.xsd"
    >
    <Attribute name="AcquireTime"         type="EPICS_PV" source="13SIM1:cam1:AcquireTime"      dbrtype="DBR_NATIVE"  description="Camera acquire time"/>
    <Attribute name="RingCurrent"         type="EPICS_PV" source="S:SRcurrentAI"                dbrtype="DBR_NATIVE"  description="Storage ring current"/>
    <Attribute name="RingCurrent_EGU"     type="EPICS_PV" source="S:SRcurrentAI.EGU"            dbrtype="DBR_NATIVE"  description="Storage ring current units"/>
    <Attribute name="ID_Energy"           type="EPICS_PV" source="ID34:Energy"                  dbrtype="DBR_NATIVE"  description="Undulator energy"/>
    <Attribute name="ID_Energy_EGU"       type="EPICS_PV" source="ID34:Energy.EGU"              dbrtype="DBR_NATIVE"  description="Undulator energy units"/>
    <Attribute name="ImageCounter"        type="PARAM"    source="ARRAY_COUNTER"                datatype="INT"        description="Image counter"/>
    <Attribute name="MaxSizeX"            type="PARAM"    source="MAX_SIZE_X"                   datatype="INT"        description="Detector X size"/>
    <Attribute name="MaxSizeY"            type="PARAM"    source="MAX_SIZE_Y"                   datatype="INT"        description="Detector Y size"/>
    <Attribute name="CameraModel"         type="PARAM"    source="MODEL"                        datatype="STRING"     description="Camera model"/>
    <Attribute name="CameraManufacturer"  type="PARAM"    source="MANUFACTURER"                 datatype="STRING"     description="Camera manufacturer"/>
    <Attribute name="Pi"                  type="FUNCTION" source="myAttrFunct1"                 param="PI"            description="Value of PI"/>
    <Attribute name="E"                   type="FUNCTION" source="myAttrFunct1"                 param="E"             description="Value of exp(1.0)"/>
    <Attribute name="Ten"                 type="FUNCTION" source="myAttrFunct1"                 param="10"            description="Value 10"/>
    <Attribute name="Gettysburg"          type="FUNCTION" source="myAttrFunct1"                 param="GETTYSBURG"    description="Start of Gettysburg address"/>
</Attributes>

I put the extra ../ADCore because I want this to be a model for other areaDetector applications like ADPilatus, and they need to find the schema file in ADCore.

I get the following error when I try to validate:

corvette:areaDetector/ADCore/iocBoot>./validateXML.sh
../iocs/simDetectorIOC/iocBoot/iocSimDetector/ROIAttributes.xml validates
../iocs/simDetectorIOC/iocBoot/iocSimDetector/netCDFAttributes.xml validates
../iocs/simDetectorIOC/iocBoot/iocSimDetector/simDetectorAttributes.xml:5: parser error : attributes construct error
    xsi:schemaLocation="xsi:noNamespaceSchemaLocation="../../../../../ADCore/ioc
                                                       ^
../iocs/simDetectorIOC/iocBoot/iocSimDetector/simDetectorAttributes.xml:5: parser error : Couldn't find end of Start Tag Attributes line 3
    xsi:schemaLocation="xsi:noNamespaceSchemaLocation="../../../../../ADCore/ioc
                                                       ^
../iocs/simDetectorIOC/iocBoot/iocSimDetector/simDetectorAttributes.xml:5: parser error : Extra content at the end of the document
    xsi:schemaLocation="xsi:noNamespaceSchemaLocation="../../../../../ADCore/ioc
                                                       ^
../iocs/simDetectorIOC/iocBoot/iocSimDetector/NexusTemplate.xml validates
../iocs/simDetectorIOC/iocBoot/iocSimDetector/hdf5_layout_demo.xml validates
../iocs/simDetectorIOC/iocBoot/iocSimDetector/hdf5_layout_nexus.xml validates


________________________________

**Comment by prjemian** [comment]
change this

 
xsi:schemaLocation="xsi:noNamespaceSchemaLocation="../../../../../ADCore/iocBoot/NDAttributes.xsd"

to this

 
xsi:noNamespaceSchemaLocation="../../../../../ADCore/iocBoot/NDAttributes.xsd"

and then ./validate.sh will succeed

**Comment by prjemian** [comment]
superceded by https://github.com/areaDetector/ADExample/issues/2
