### ISSUE TITLE
NDFileHDF5: Automatically append attribute "units" when available in PV EGU field

### ISSUE THREAD

**Issue by jilavsky** [areaDetector/ADCore#422]
Request for improvement: 

For values coming from PVs we often have EGU field which should contain units string. Units are kind of important for downstream software as it should be doing proper conversions. Examples abound, e.g., motor positions (distance) needs to be interpreted as mm, m, cm, A, nm... Temperature, angles, time... 

At this time we have to add multiple lines in template to add attribute units with value from .EGU field which makes templates quite complicated.  Can we add "units" attribute automatically to each value when EGU field available and not empty? 

As physicist, I was told that a value without unit is meaningless.  Forcing users to have units should be the default option.

**Comment by MarkRivers** [comment]
> Can we add "units" attribute automatically to each value when EGU field available and not empty?

While this seems nice I don't think it is very practical.  Consider the attribute 13SIM1:cam1:Model_RBV which gives the camera model.  This is a stringin record that does not have an EGU field.  There are 2 options that I know of to determine whether there is an EGU field for this PV:
- Try to read the EGU field with Channel Access.  Since it won't exist this will incur a time delay of the channel access timeout, which may be several seconds.  This delay will be incurred for all PVs that don't have EGU fields.
- Build the knowledge of all record types into areaDetector so that first it reads the RTYP to determine whether there is an EGU field, and then reads the field.  This would be a lot of work and hard to maintain.

There is also the problem that there is only one EGU field per record, even though there may be many fields that have engineering units.  Consider the motor record.  What if I want to save the ACCL field of the motor record, and my motor record has EGU=mm.  Now the ACCL field will put EGU=mm in the HDF5 file, which is incorrect.  The correct units for ACCL is seconds.
