### ISSUE TITLE
rst flat-table

### ISSUE THREAD

**Issue by hinxx** [areaDetector/ADCore#431]
More of a question than bug report.

Which part of the docs generation is dealing with flat-table conversion to HTML?

I'm looking into using RST for docs for driver I write. I managed to get some insight by looking at the travis CI on how the whole is done and it looks quite involved. Is it reStructuredText that I need look into or Sphinx, or some other thing? I might skip the whole doxygen integration at the start..

**Comment by MarkRivers** [comment]
Sphinx does the conversion of flat-table to HTML.

flat-table is very similar to list-table, the thing it add that I wanted in some cases is the ability to span columns.  This allows sub-headings in the table.  But flat-table is not part of standard Sphinx, so it is some work to include it. I suggest using list-tables instead.

areaDetector Sphinx documentation is more complex than most, because it is building a single  document tree from multiple repositories.  If you just need to document a single repository it is much simpler to use readthedocs.org.  You don't need a travis job.  It uses Webhooks.  It's just a bit of configuration on both the readthedocs Web site and the Github web site.

Here is an example:

https://github.com/epics-modules/Dante
https://epics-dante.readthedocs.io/en/latest/

Mark

**Comment by hinxx** [comment]
Thanks @MarkRivers ! I managed to get sphinx and flat-table working for my project by hacking what is in AD repos. readthedocs.org looks promising (I noticed CS Studio also uses it AFAICT), but my use case might need to have these docs available on the internal network with no internet access.

**Comment by MarkRivers** [comment]
> readthedocs.org looks promising (I noticed CS Studio also uses it AFAICT), but my use case might need to have these docs available on the internal network with no internet access.

It's not a problem to have the docs available on the internal network.  

These are the docs on readthedocs.org for a project I just finished:
https://tomoscan.readthedocs.io/en/latest/

This is the source for that project, with a docs/ directory:
https://github.com/tomography/tomoscan

The tomoscan/docs directory contains this Makefile:
https://github.com/tomography/tomoscan/blob/master/docs/Makefile

If you run that Makefile locally it will build the documentation with Sphinx and put the output in /tomoscan/docs/_build/html/.  You can just copy that directory to you local Web server.
